#version: '3.8'
#
#services:
#  mysql:
#    image: mysql:latest
#    container_name: mysql-container
#    restart: always
#    ports:
#      - "3307:3306"
#    environment:
#      MYSQL_DATABASE: mydatabase
#      MYSQL_USER: myuser
#      MYSQL_PASSWORD: secret
#      MYSQL_ROOT_PASSWORD: verysecret
#    volumes:
#      - mysql_data:/var/lib/mysql
#
#volumes:
#  mysql_data:
#
#
##pour demarrer docker
##  docker-compose up -d
